### ISSUE TITLE
Request of pre-trained model

### ISSUE THREAD

**Issue by MrTornado24** [jgkwak95/SURF-GAN#1]
Hi, nice work! I notice that FIDs of Surf-gan look great. Could you provide the pre-trained model which is trained on FFHQ@256?

**Comment by jgkwak95** [comment]
Hi, thanks for your attention and i read your research before (FENeRF) interestingly! 

To provide a pretrained model, we have to retrain the model because we changed name of variables and models for code cleaning and uploading. We will provide the pretrained model of CelebA and FFHQ before ECCV conf.
