### ISSUE TITLE
How to use the pre-training model to generate other images?

### ISSUE THREAD

**Issue by hxl835097324** [jgkwak95/SURF-GAN#7]
Hi @jgkwak95,
thanks a lot for sharing the code for your work. When I was learning your project code, I didn't find a place to input my own pictures.

Thank you very much !

**Comment by hxl835097324** [comment]
zs = sample_latent((num_id, 9, 6), device=device, truncation=opt.psi)
Is it this line of code?

**Comment by jgkwak95** [comment]
Hi @hxl835097324, Thanks for your attention.

SURF-GAN generator is a random image generator which takes a latent vector as input. 
Of course you can find a target latent vector through GAN inversion, but the results will probably be bad because of low resolution.  That is why we distilled to StyleGAN.
